export const ActionTypes = {
  GET_GENRES: "GET_GENRES",
  CREATE_VIDEOGAME: "CREATE_VIDEOGAME",
  GET_VIDEOGAMES: "GET_VIDEOGAMES",
  ORDER_VIDEOGAMES: "ORDER_VIDEOGAMES",
  SEARCH_VIDEOGAMES: "SEARCH_VIDEOGAMES",
  VIDEOGAME_DETAIL: "VIDEOGAME_DETAIL",
  FILTER_VIDEOGAMES: "FILTER_VIDEOGAMES",
  DELETE_VIDEOGAME: "DELETE_VIDEOGAME",
};
